### ISSUE TITLE
Cannot clear cache

### ISSUE THREAD

**Issue by SamMakesCode** [anrip/cordova-plugin-cache-clear#3]
Hey all,

I've created a button that on click would perform a login API call. I decided to change the <button> to a div in an attempt to fix some apparent bug with jQuery's onclick not working with phonegap.

I have the following setup:
- Phonegap 1.7.10 app on iOS
- Phonegap CLI 7.0.0 on Windows 10
- this plugin at 1.3.7

And I can't seem to clear the cache at all. I've got this code...

    document.addEventListener('deviceready', function () {
        var success = function(status) {
            alert('Message: ' + status);
        };
        var error = function(status) {
            alert('Error: ' + status);
        };
        window.CacheClear(success, error);
    });

And yet everytime I fire up the iOS app to test it, I get the HTML button. Any ideas?

Many thanks,

Sam

**Comment by SamMakesCode** [comment]
Additionally (it may be helpful), these caching problems don't seem to affect CSS/images the same way.

**Comment by rehiy** [comment]
I test it in ionic, i can clear the storage cache data.

**Comment by SamMakesCode** [comment]
So for anyone who comes here after me... I had auto-reload disabled when running phonegap on the command line.

Normally, when you make a change, phonegap detects it and "re-caches" the files into another folder. With auto-reload disabled, this doesn't happen and so you ended up running of the same version every time.

I didn't actually need this plugin, I just needed to use phonegap in a documented manner.
